# -*- coding: utf-8 -*-
"""PRACTICA_STARWARS_FINAL_Jay_Shankar_Cangi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MsQCw87pShwzfPqN5-X6to_3j4E4Z3tt
"""

pip install art

from art import *
import time as time


# LA CLASE JEDI
class jedi():
    diccionario_jedi = {'nombre': ['Obi-Wan Kenobi', 'Anakin Skywalker', 'Yoda', 'Luke Skywalker'],
                        'rango': ['Maestro', 'Caballero', 'Maestro', 'Maestro'],
                        'poder': [90, 95, 100, 85]}


# LA CLASE SITH
class sith():
    diccionario_sith = {'nombre': [' Darth Vader', 'Dath Sidious', 'Darth Maul'],
                        'rango': ['Lord Sith', 'Lord Sith', 'Lord Sith'],
                        'poder': [90, 100, 85]}


# CLASE PRINCIPAL / PANTALLA MENU
class principal():
    def menu():
        # MENU PRINCIPAL
        ag = agenda()
        while True:
            opciones = ['Añadir nuevo Jedi/Sith', 'Modificar Jedi/Sith', "Consultar Jedi/Sith", "Eliminar Jedi/Sith",
                        'Listar Todos Los Contactos', "Exit"]

            print('    ')
            ascii_art = text2art('STAR WARS')
            print(ascii_art)
            print("********** MENU **********")
            # SE IMPRIME EL MENU PRINCIPAL
            for i in (range(len(opciones))):
                print(f'{1 + i} - {opciones[i]}')

            ch = input("\nSeleccione una opción: ")

            while ch not in ['1', '2', '3', '4', '5', '6']:
                print('Error al seleccionar una opción')
                ch = input('Seleccione una opción: \n')

            # AÑADIR PERSONAJES
            else:
                if ch == '1':
                    nombre = input('Introduzca el nombre del personaje: \n')
                    while not nombre.isalpha():
                        nombre = input('Introduzca el nombre del personaje (SOLO CON LETRAS):\n')
                    else:
                        tipo = input('Escoga el tipo de personaje (Jedi/Sith): \n')
                        while tipo.lower() not in ['jedi', 'sith']:
                            tipo = input(
                                'El tipo de personaje no es valido. \n Escoga el tipo de personaje (Jedi/Sith): \n').lower()
                        else:
                            if tipo.lower() == 'jedi':
                                ag.anadir_jedi(nombre, jedi)

                            elif tipo.lower() == 'sith':
                                ag.anadir_sith(nombre, sith)

                # MODIFICAR PERSONAJES
                elif ch == '2':
                    nombre = input('Introduzca el nombre del personaje que quiera modificar: \n')
                    while not nombre.isalpha():
                        nombre = input('Introduzca el nombre del personaje que quiera modificar (SOLO CON LETRAS):\n')
                    else:
                        ag.modificar(nombre)

                # CONSULTAR PERSONAJES
                elif ch == '3':
                    busqueda = input("¿Desea buscar por nombre, rango o poder? \n ")
                    bus_queda = ['nombre', 'rango', 'poder']
                    while busqueda.lower() not in bus_queda:
                        busqueda = input(
                            'PORFAVOR INTRODUZCA UNA DE LAS SIGUIENTES OPCIONES: \n-Nombre \n -Rango \n -Poder \n')
                    else:
                        ag.consultar(busqueda)

                # ELIMINAR PERSONAJES
                elif ch == '4':
                    nombre = input('Introduzca el nombre del personaje que quiera eliminar: \n').capitalize()
                    while not nombre.isalpha():
                        nombre = input('Introduzca el nombre del personaje que quiera eliminar (SOLO CON LETRAS):\n').capitalize()
                    else:
                        ag.eliminar(nombre)

                # LISTAR TODOS LOS CONTACTOS
                elif ch == '5':
                    ag.todos()

                # SALIR
                elif ch == '6':
                    print('¡¡QUE LA FUERZA TE ACOMPAÑE!!')
                    time.sleep(3)
                    break
                    break
                    exit


class agenda(principal, jedi, sith):
    # Añadir Jedi
    # SE REVISA SI EL DICCIONARIO ESTA LLENO, DE NO SER ASI SE AÑADE EL PERSONAJE A JEDI CON CONFIRMACIÓN DEL USUARIO
    # EL USUARIO INGRESA EL RANGO Y EL PODER DEL PERSONAJE
    def anadir_jedi(self, nombre, jedi):
        if len(jedi.diccionario_jedi['nombre']) == 50:
            print('LA AGENDA ESTA LLENA. ELIMINE ALGUNOS CONTACTOS PARA CONTINUAR')
            time.sleep(2)
        else:
            rango_j = ['padawan', 'caballero', 'maestro']
            if nombre.capitalize() in jedi.diccionario_jedi['nombre']:
                print('Este personaje ya existe')
                time.sleep(1)
                principal.menu()
            else:
                rango_jedi = input('Introduzca el rango Padawan,Caballero o Maestro: \n').capitalize()
                while rango_jedi.lower() not in rango_j:
                    rango_jedi = input(
                        'El rango es invalido, escoga uno de los siguientes: Padawan, Caballero, Maestro: \n').capitalize()
                else:
                    poder_j = input(f'Introduzca el poder 0 - 100: \n')
                    while not poder_j.isdigit() or int(poder_j) < 0 or int(poder_j) > 100:
                        poder_j = input('El valor introducido no es valido. \n Escoga un numero entre 0 y 100 : \n')

                    else:
                        print(
                            f'El personaje que va a añadir:\n NOMBRE:{nombre.capitalize()} \n RANGO: {rango_jedi.capitalize()} \n PODER:{poder_j} \n')
                        time.sleep(1)
                        opcion = input('Seguro que quiere añadir a este personaje? S/N : \n')
                        while opcion.lower() not in ['s', 'n']:
                            opcion = input(
                                'El valor introducido no es valido. \nEscoga uno de los siguientes: S/N : \n')
                        else:
                            if opcion.lower() == 's':
                                self.diccionario_jedi['nombre'].append(nombre.capitalize())
                                self.diccionario_jedi['rango'].append(rango_jedi.capitalize())
                                self.diccionario_jedi['poder'].append(poder_j)
                                print(f'BIENVENID@ {nombre} A LA FUERZA')
                                time.sleep(1)
                            if opcion.lower() == 'n':
                                print('OPERACIÓN CANCELADA')
                                principal.menu()

    # Añadir Sith
    def anadir_sith(self, nombre, sith):
        # SE REVISA SI EL DICCIONARIO ESTA LLENO, DE NO SER ASI SE AÑADE EL PERSONAJE A SITH CON CONFIRMACIÓN DEL USUARIO
        # EL USUARIO INGRESA EL RANGO Y EL PODER DEL PERSONAJE
        if len(sith.diccionario_sith['nombre']) == 50:
            print('LA AGENDA ESTA LLENA. ELIMINE ALGUNOS CONTACTOS PARA CONTINUAR')
            time.sleep(2)
        else:
            rango_s = ['aprendiz', 'darth', 'lord sith']
            if nombre.capitalize() in sith.diccionario_sith['nombre']:
                print('Este personaje ya existe')
                time.sleep(1)
                principal.menu()
            else:
                rango_sith = input('Introduzca el rango (Aprendiz, Darth, Lord Sith): \n').capitalize()
                while rango_sith.lower() not in rango_s:
                    rango_sith = input(
                        'El rango es invalido, escoga uno de los siguientes (Aprendiz, Darth, Lord Sith): \n').capitalize()
                else:
                    poder_s = input(f'Introduzca el poder 0 - 100: \n')
                    while not poder_s.isdigit() or int(poder_s) < 0 or int(poder_s) > 100:
                        poder_s = input('El valor introducido no es valido. \n Escoga un numero entre 0 y 100 : \n')

                    else:
                        print(
                            f'El personaje que va a añadir:\n NOMBRE:{nombre.capitalize()} \n RANGO: {rango_sith.capitalize()} \n PODER:{poder_s} \n')
                        opcion = input('Seguro que quiere añadir a este personaje? S/N : \n')

                        while opcion.lower() not in ['s', 'n']:
                            opcion = input(
                                'El valor introducido no es valido. \n Escoga uno de los siguientes: S/N : \n')
                        else:
                            if opcion.lower() == 's':
                                self.diccionario_sith['nombre'].append(nombre.capitalize())
                                self.diccionario_sith['rango'].append(rango_sith.capitalize())
                                self.diccionario_sith['poder'].append(poder_s)
                                print(f'BIENVENID@ {nombre} AL LADO OSCURO')
                                time.sleep(1)

                            if opcion.lower() == 'n':
                                print('OPREACIÓN CANCELADA')
                                time.sleep(1)
                                principal.menu()

    # MODIFICAR PERSONAJE
    def modificar(self, nombre):
        encontrado = False

        # BUSCAR EL NOMBRE EN JEDI, SI EXISTE EN EL DICCIONARIO SE MODIFICA
        for i in range(len(jedi.diccionario_jedi['nombre'])):
            if jedi.diccionario_jedi['nombre'][i] == nombre.capitalize():
                encontrado = True
                print("Jedi encontrado:")
                print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                print("Rango: ", jedi.diccionario_jedi['rango'][i])
                print("Poder: ", jedi.diccionario_jedi['poder'][i])
                time.sleep(2)

                rango_jedi = input('Introduzca el nuevo rango (Padawan,Caballero o Maestro): \n').capitalize()
                rango_j = ['padawan', 'caballero', 'maestro']
                while rango_jedi.lower() not in rango_j:
                    rango_jedi = input(
                        'El rango es invalido, escoga uno de los siguientes: Padawan, Caballero, Maestro: \n').capitalize()
                else:
                    poder_jedi = input(f'Introduzca el nuevo poder 0 - 100: \n')
                    while not poder_jedi.isdigit() or int(poder_jedi) < 0 or int(poder_jedi) > 100:
                        poder_jedi = input('El valor introducido no es valido. \n Escoga un numero entre 0 y 100 : \n')
                    else:
                        jedi.diccionario_jedi['rango'][i] = rango_jedi
                        jedi.diccionario_jedi['poder'][i] = poder_jedi
                        print("Jedi modificado:")
                        print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                        print("Rango: ", jedi.diccionario_jedi['rango'][i])
                        print("Poder: ", jedi.diccionario_jedi['poder'][i])
                        time.sleep(3)
                        break

        # SI NO SE HA ENCONTRADO EL NOMBRE EN JEDI, SE BUSCA EN SITH Y SE MODIFICA
        if not encontrado:
            for i in range(len(sith.diccionario_sith['nombre'])):
                if sith.diccionario_sith['nombre'][i] == nombre.capitalize():
                    encontrado = True
                    print("Sith encontrado:")
                    print("Nombre: ", sith.diccionario_sith['nombre'][i])
                    print("Rango: ", sith.diccionario_sith['rango'][i])
                    print("Poder: ", sith.diccionario_sith['poder'][i])
                    time.sleep(2)

                    rango_sith = input("Ingrese el nuevo rango para el Sith: ")
                    rango_s = ['aprendiz', 'darth', 'lord sith']
                    while rango_sith.lower() not in rango_s:
                        rango_sith = input(
                            'El rango es invalido, escoga uno de los siguientes (Aprendiz, Darth, Lord Sith): \n')
                    else:
                        poder_sith = input("Ingrese el nuevo poder para el Sith: ")
                        while not poder_sith.isdigit() or int(poder_sith) < 0 or int(poder_sith) > 100:
                            poder_sith = input(
                                'El valor introducido no es valido. \n Escoga un numero entre 0 y 100 : \n')

                        else:
                            sith.diccionario_sith['rango'][i] = rango_sith
                            sith.diccionario_sith['poder'][i] = poder_sith
                            print("Sith modificado:")
                            print("Nombre: ", sith.diccionario_sith['nombre'][i])
                            print("Rango: ", sith.diccionario_sith['rango'][i])
                            print("Poder: ", sith.diccionario_sith['poder'][i])
                            time.sleep(3)
                            break

            # SI NO SE HA ENCONTRADO EL NOMBRE EN JEDI NI EN SITH, SE IMPRIME ESTE ERROR
            if not encontrado:
                print("No se encontró ningún personaje con ese nombre.")
                time.sleep(1)

    # CONSULTAR PERSONAJE
    def consultar(self, busqueda):
        encontrado = False
        # CONSULTAR PERSONAJES POR NOMBRE
        if busqueda.lower() == 'nombre':
            nombre = input('Introduzca el nombre del personaje: \n')

            for i in range(len(jedi.diccionario_jedi['nombre'])):
                if jedi.diccionario_jedi['nombre'][i] == nombre:
                    encontrado = True
                    print("Jedi encontrado:")
                    print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                    print("Rango: ", jedi.diccionario_jedi['rango'][i])
                    print("Poder: ", jedi.diccionario_jedi['poder'][i])
                    print('\n')
                    time.sleep(1)

            for i in range(len(sith.diccionario_sith['nombre'])):
                if sith.diccionario_sith['nombre'][i] == nombre:
                    encontrado = True
                    print("Sith encontrado:")
                    print("Nombre: ", sith.diccionario_sith['nombre'][i])
                    print("Rango: ", sith.diccionario_sith['rango'][i])
                    print("Poder: ", sith.diccionario_sith['poder'][i])
                    print('\n')
                    time.sleep(1)
            if not encontrado:
                print("No se encontró ningún personaje que coincida con la búsqueda.")
                time.sleep(1)

        # CONSULTAR PERSONAJES POR RANGO
        if busqueda.lower() == 'rango':
            rango = input(
                'Escoga uno de los siguientes rangos: \n - Padawan \n - Caballero \n - Maestro \n - Aprendiz \n - Darth \n - Lord Sith \n')

            while rango.lower() not in ['padawan', 'caballero', 'maestro', 'aprendiz', 'darth', 'lord sith']:

                rango = input(
                    'El rango es invalido, escoga uno de los siguientes: \n -Padawan \n -Caballero \n -Maestro \n -Aprendiz \n -Darth \n -Lord Sith: \n')

            else:

                for i in range(len(jedi.diccionario_jedi['rango'])):
                    if jedi.diccionario_jedi['rango'][i] == rango.capitalize():
                        encontrado = True
                        print("Jedi encontrado:")
                        print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                        print("Rango: ", jedi.diccionario_jedi['rango'][i])
                        print("Poder: ", jedi.diccionario_jedi['poder'][i])
                        print('\n')
                        time.sleep(1)

                for i in range(len(sith.diccionario_sith['rango'])):
                    if sith.diccionario_sith['rango'][i] == rango.capitalize() or rango.title() == 'Lord Sith':
                        encontrado = True
                        print("Sith encontrado:")
                        print("Nombre: ", sith.diccionario_sith['nombre'][i])
                        print("Rango: ", sith.diccionario_sith['rango'][i])
                        print("Poder: ", sith.diccionario_sith['poder'][i])
                        print('\n')
                        time.sleep(1)

                if not encontrado:
                    print("No se encontró ningún personaje que coincida con la búsqueda.")
                    time.sleep(1)

        # CONSULTAR PERSONAJES POR PODER
        if busqueda.lower() == 'poder':
            poder = input(f'Introduzca el poder 0 - 100: \n')
            while not poder.isdigit() or int(poder) < 0 or int(poder) > 100:
                poder = input('El valor introducido no es valido. \n Escoga un numero entre 0 y 100 : \n')
            else:
                for i in range(len(jedi.diccionario_jedi['poder'])):
                    if jedi.diccionario_jedi['poder'][i] == poder:
                        encontrado = True
                        print("Jedi encontrado:")
                        print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                        print("Rango: ", jedi.diccionario_jedi['rango'][i])
                        print("Poder: ", jedi.diccionario_jedi['poder'][i])
                        print('\n')
                        time.sleep(1)

                for i in range(len(sith.diccionario_sith['nombre'])):
                    if sith.diccionario_sith['poder'][i] == poder:
                        encontrado = True
                        print("Sith encontrado:")
                        print("Nombre: ", sith.diccionario_sith['nombre'][i])
                        print("Rango: ", sith.diccionario_sith['rango'][i])
                        print("Poder: ", sith.diccionario_sith['poder'][i])
                        print('\n')
                        time.sleep(1)

                if not encontrado:
                    print("No se encontró ningún personaje que coincida con la búsqueda.")
                    time.sleep(1)

        if busqueda.lower() != 'nombre' and busqueda.lower() != 'rango' and busqueda.lower() != 'poder':
            print("Opción no válida.")
            time.sleep(1)

    # ELIMINAR PERSONAJE
    def eliminar(self, nombre):
        encontrado_jedi = False
        encontrado_sith = False
        '''
        #Buscamos si el personaje existe en ambas listas'
        for i in range(len(sith.diccionario_sith['nombre'])) and range(len(jedi.diccionario_jedi['nombre'])):
          if encontrado_jedi == True  and encontrado_sith == True:
            print("El personaje se encontró en ambas listas.")
            eleccion = input("¿Desea eliminar al personaje de la lista Jedi (j) o Sith (s)?: ")

            if eleccion == 'j':
                del jedi.diccionario_jedi['nombre'][i]
                del jedi.diccionario_j
                print("Jedi eliminado.")
                time.sleep(1)

            elif eleccion == 's':
                del sith.diccionario_sith['nombre'][i]
                del sith.diccionario_sith['rango'][i]
                del sith.diccionario_sith['poder'][i]
                print("Sith eliminado.")
                time.sleep(1)
        '''

        # Busca el personaje en el diccionario Jedi
        for i in range(len(jedi.diccionario_jedi['nombre'])):
            if jedi.diccionario_jedi['nombre'][i] == nombre:
                encontrado_jedi = True
                print("Jedi encontrado:")
                print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
                print("Rango: ", jedi.diccionario_jedi['rango'][i])
                print("Poder: ", jedi.diccionario_jedi['poder'][i])
                time.sleep(1)

                #  Confirmar si de verdad quiere eliminar el personaje
                confirmacion = input("¿Está seguro de que desea eliminar este personaje? (s/n): ")
                while confirmacion.lower() not in ['s', 'n']:
                    confirmacion = input("¿Está seguro de que desea eliminar este personaje? (s/n): ")
                else:
                    if confirmacion == 's':
                        # Elimina al personaje del diccionario Jedi
                        del jedi.diccionario_jedi['nombre'][i]
                        del jedi.diccionario_jedi['rango'][i]
                        del jedi.diccionario_jedi['poder'][i]
                        print("Jedi eliminado.")
                        time.sleep(1)
                    else:
                        print("El personaje no ha sido eliminado.")
                        time.sleep(1)

                    break

        # Busca el personaje en el diccionario Sith si no lo ha encontrado en Jedi

        for i in range(len(sith.diccionario_sith['nombre'])):
            if sith.diccionario_sith['nombre'][i] == nombre.capitalize():
                encontrado: sith = True
                print("Sith encontrado:")
                print("Nombre: ", sith.diccionario_sith['nombre'][i])
                print("Rango: ", sith.diccionario_sith['rango'][i])
                print("Poder: ", sith.diccionario_sith['poder'][i])
                time.sleep(1)

                # Confirmar si de verdad quiere eliminar el personaje
                confirmacion = input("¿Está seguro de que desea eliminar este personaje? (s/n): ")
                while confirmacion.lower() not in ['s', 'n']:
                    confirmacion = input("¿Está seguro de que desea eliminar este personaje? (s/n): ")
                else:
                    if confirmacion == 's':
                        # Elimina al personaje del diccionario Sith
                        del sith.diccionario_sith['nombre'][i]
                        del sith.diccionario_sith['rango'][i]
                        del sith.diccionario_sith['poder'][i]
                        print("Sith eliminado.")
                        time.sleep(1)

                    if confirmacion == 'n':
                        print("El personaje no ha sido eliminado.")
                        time.sleep(1)
                        break

        # Si no ha encontrado el nombre en ningun diccionario
        if not encontrado_jedi and not encontrado_sith:
            print("No se encontró ningún personaje con ese nombre.")
            time.sleep(1)

    def todos(self):
        # Imprimir todos los Jedi del diccionario
        tprint("Jedi: \n")
        for i in range(len(jedi.diccionario_jedi['nombre'])):
            print("Nombre: ", jedi.diccionario_jedi['nombre'][i])
            print("Rango: ", jedi.diccionario_jedi['rango'][i])
            print("Poder: ", jedi.diccionario_jedi['poder'][i])
            print('\n')
            time.sleep(1)

        # Imprimir todos los Sith del diccionario
        tprint("\nSith: \n")
        for i in range(len(sith.diccionario_sith['nombre'])):
            print("Nombre: ", sith.diccionario_sith['nombre'][i])
            print("Rango: ", sith.diccionario_sith['rango'][i])
            print("Poder: ", sith.diccionario_sith['poder'][i])
            print('\n')
            time.sleep(1)

        return


# Inicio
print('\n')
print(f""" ⠀			   /~\   Hola Ana, soy C-3PO. ¿En qué puedo ayudarte?
                          (O O) _/
                          _\=/_
          ___            /  _  \
         / ()\          //|/.\|\\
       _|_____|_       ||  \_/  ||
      | | === | |      || |\ /| ||
      |_|  O  |_|       # \_ _/ #
       ||  O  ||          | | |
       ||__*__||          | | |
      |~ \___/ ~|         []|[]
      /=\ /=\ /=\         | | |
______[_]_[_]_[_]________/_]_[_\_____""")
time.sleep(2)
principal.menu()